# Generated by Django 5.0 on 2024-09-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='rating_event',
            new_name='rating_count',
        ),
    ]
